name: Create Sentry release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of this release in the Homey App Store'
        required: true

jobs:
  sentry-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          version: ${{ github.event.inputs.version }}
